# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'case-study4' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for case-study4
  # Add the pods for the Firebase products you want to use in your app
  # For example, to use Firebase Authentication and Cloud Firestore
  pod 'FirebaseAuth'
  pod 'FirebaseFirestore'
  pod 'FirebaseMessaging'

  target 'case-study4Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'case-study4UITests' do
    # Pods for testing
  end

end
